/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#303038",
        "on-tertiary": "#3c0091",
        "surface-variant": "#34343d",
        "background": "#13131b",
        "outline-variant": "#464554",
        "on-primary-fixed": "#07006c",
        "on-surface": "#e4e1ed",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-bright": "#393841",
        "surface-container-lowest": "#0d0d15",
        "surface": "#13131b",
        "error-container": "#93000a",
        "on-primary-container": "#0d0096",
        "on-secondary-fixed": "#001f26",
        "primary-fixed": "#e1e0ff",
        "surface-container": "#1f1f27",
        "tertiary-container": "#a078ff",
        "tertiary-fixed-dim": "#d0bcff",
        "secondary": "#4cd7f6",
        "on-surface-variant": "#c7c4d7",
        "on-tertiary-container": "#340080",
        "error": "#ffb4ab",
        "secondary-fixed": "#acedff",
        "tertiary": "#d0bcff",
        "primary-fixed-dim": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#00424e",
        "surface-container-low": "#1b1b23",
        "on-background": "#e4e1ed",
        "inverse-primary": "#494bd6",
        "surface-tint": "#c0c1ff",
        "surface-container-highest": "#34343d",
        "primary": "#c0c1ff",
        "primary-container": "#8083ff",
        "inverse-surface": "#e4e1ed",
        "tertiary-fixed": "#e9ddff",
        "on-secondary": "#003640",
        "surface-container-high": "#292932",
        "on-primary": "#1000a9",
        "surface-dim": "#13131b",
        "secondary-container": "#03b5d3",
        "secondary-fixed-dim": "#4cd7f6",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#2f2ebe",
        "outline": "#908fa0",
        "on-tertiary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#004e5c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "base": "4px",
        "lg": "1.5rem",
        "md": "1rem",
        "container-max": "1280px",
        "2xl": "4rem",
        "xl": "2.5rem",
        "xs": "0.25rem",
        "sm": "0.5rem"
      },
      fontFamily: {
        "label-sm": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "mono-label": ["Geist", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "mono-label": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.04em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
